export type Buttons = {
  left: boolean;
  right: boolean;
  thrust: boolean;
  fire: boolean;
  hyper: boolean;
  /** Dock DIP5 down = attract test (board: dip5_test = ~dip5_n). */
  dip5Down: boolean;
};
export type Shot = {
  on: boolean;
  x: number;
  y: number;
  vx: number;
  vy: number;
  life: number;
};
export type GameState = {
  pos0x: number;
  pos0y: number;
  pos1x: number;
  pos1y: number;
  vel0x: number;
  vel0y: number;
  vel1x: number;
  vel1y: number;
  ang0: number;
  ang1: number;
  thrusting0: boolean;
  thrusting1: boolean;
  shots: Shot[];
  score0: number;
  score1: number;
  lives0: number;
  fuelMs: number;
  timer: number;
  frameCnt: number;
  playSec: number;
  gameOver: boolean;
  awaitStart: boolean;
  testMode: boolean;
  blackHole: boolean;
  antiGrav: boolean;
  antiGravSec: number;
  sunHits: number;
  bhHits: number;
  spawn0: number;
  spawn1: number;
  spawnThr0: number;
  spawnThr1: number;
  vanish0: number;
  vanish1: number;
  hsPhase: 0 | 1 | 2;
  hsFr: number;
  hsRed: boolean;
  fireHold: boolean;
  firePrev: boolean;
  fireCd: number;
  fireReload: number;
  fireMag: number;
  hyperPrev: boolean;
  aiCd: number;
  aiReload: number;
  aiMag: number;
  aiStreak: number;
  shipLock: boolean;
  lfsr: number;
  playCap: number;
  aiWild: boolean;
  aiLifeN: number;
  aiStandoff: number;
  aimPct: number;
  aiThrust: number;
  aiDec: number;
  demoModeR: boolean;
  plInvuln: boolean;
  aiInvuln: boolean;
  sunNear0: boolean;
  sunNear1: boolean;
  wallNear0: boolean;
  wallNear1: boolean;
  starPanX: number;
  starPanY: number;
  starDx: number;
  starDy: number;
  starDirTmr: number;
  starLfsr: number;
};
export function demoMode(s: GameState): boolean {
  return s.gameOver || s.awaitStart;
}
